### ISSUE TITLE
AI grid cells spanning multiple columns/rows

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/akgfmaps#106]
### Issue
In the AI, two ID cell grids (98-19 and 41-48) span across multiple grid cells. 

```
library(akgfmaps)

ai_grid_3338 <- akgfmaps::get_base_layers(select.region = "ai", set.crs = "EPSG:3338")$survey.grid

ai_grid_union <- dplyr::select(ai_grid_3338, ID) |>
  dplyr::group_by(ID) |>
  summarise()

ai_grid_union$area <- sf::st_area(ai_grid_union)

ggplot() +
  geom_sf(data = dplyr::arrange(ai_grid_union, -area)[1,],
          linewidth = 3) +
  geom_sf_text(data = dplyr::arrange(ai_grid_union, -area)[1,] |>
            sf::st_centroid(),
            mapping = aes(label = ID))

ggplot() +
  geom_sf(data = dplyr::arrange(ai_grid_union, -area)[2,],
          linewidth = 3) +
  geom_sf_text(data = dplyr::arrange(ai_grid_union, -area)[2,] |>
                 sf::st_centroid(),
               mapping = aes(label = ID))
```

![image](https://github.com/afsc-gap-products/akgfmaps/assets/65584161/7b4bf947-ca27-48c9-ba99-410306698438)

![image](https://github.com/afsc-gap-products/akgfmaps/assets/65584161/f2b5d33a-e6fd-4b3a-869e-b257ffac38f2)

**Comment by Ned-Laman-NOAA** [comment]
Since these changes are in the Aleutians, I'd like to have Susanne take a look and make sure she's ok with these changes.

**Comment by sean-rohan-NOAA** [comment]
Adding some info about these grid cells.

Based on GPS data, no tows have been conducted in AIGRID_ID 9969. Three crossed into 7138 (HAULJOIN 25191, 1139178, -12397), but none were assigned to station 98-19, stratum 413. 

Haul records for tow tow paths that crossed into 7138 are in this csv: [grid_7138_hauls.csv](https://github.com/user-attachments/files/18167751/grid_7138_hauls.csv)

There are no records 

![Image](https://github.com/user-attachments/assets/dd5d7663-e936-4d71-9e18-2415c1c661d3)

![Image](https://github.com/user-attachments/assets/e173da81-9365-47d1-8073-f9e35d1b12d1)

**Comment by smcdermo** [comment]
Hi Sean
I just talked to Ned and we both agree that we support these changes and they should be made.
Thanks for diving into the data to illustrate the tows.

Susanne

**Comment by Ned-Laman-NOAA** [comment]
Now that these changes have been approved, I will make them in the appropriate spatial tables on the Oracle server in the AI schema. Currently, Zack's station allocation code relies on the spatial resources in the AI schema, so technically these tables aren't deprecated...yet.

After talking to Zack, I don't believe that there are concurrent changes necessary in the GAP_PRODUCTS schema objects.

It looks like, from Sean's analyses, that there are NOT any stationid/stratum changes necessary in RACE_DATA.HAULS or RACEBase.HAUL since no stations were assigned to the station grid chunks we are renaming. That's good news that we aren't orphaning any past hauls with this change.

I'll post here when the changes have been made on my end.
