### ISSUE TITLE
401 error on akgfmaps and coldpool

### ISSUE THREAD

**Issue by kholsman** [afsc-gap-products/akgfmaps#39]
might be on my end: same error for all versions of the following:

devtools::install_github("afsc-gap-products/akgfmaps", build_vignettes = TRUE, R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 49/60
  Rate limit reset at: 2023-10-26 22:23:36 UTC

Same for this:
devtools::install_github("afsc-gap-products/coldpool")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 47/60
  Rate limit reset at: 2023-10-26 22:23:36 UTC

Running: 
R.Version()
$platform
[1] "x86_64-apple-darwin15.6.0"

$arch
[1] "x86_64"

$os
[1] "darwin15.6.0"

$system
[1] "x86_64, darwin15.6.0"

$status
[1] ""

$major
[1] "3"

$minor
[1] "5.3"

$year
[1] "2019"

$month
[1] "03"

$day
[1] "11"

$`svn rev`
[1] "76217"

$language
[1] "R"

$version.string
[1] "R version 3.5.3 (2019-03-11)"

$nickname
[1] "Great Truth"

**Comment by kholsman** [comment]
following up - looks to be an issue on my end with devtools maybe?

**Comment by sean-rohan-NOAA** [comment]
@kholsman I've found that error usually occurs when GitHub caps your downloads because there isn't a valid GitHub Personal Access Token in your R Environment. I think sometimes the error will occur with the akgfmaps package but not other packages because the akgfmaps is considerably larger than most packages. 

However, it also looks like you're running 3.5.3 (because of MRAN?), which isn't compatible with the akgfmaps or coldpool package. Both packages currently support R >= 4.0.

If you only need the shapefiles from akgfmaps, you can download them from (the inst/extdata directory in akgfmaps)[https://github.com/afsc-gap-products/akgfmaps/tree/master/inst/extdata].

Data built into the coldpool package data are available [here](https://github.com/afsc-gap-products/coldpool/blob/main/R/sysdata.rda).
